import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f7f9fd",
        "surface-dim": "#d8dade",
        "surface-bright": "#f7f9fd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f8",
        "surface-container": "#eceef2",
        "surface-container-high": "#e6e8ec",
        "surface-container-highest": "#e0e3e6",
        "on-surface": "#181c1f",
        "on-surface-variant": "#45464d",
        "inverse-surface": "#2d3134",
        "inverse-on-surface": "#eff1f5",
        outline: "#76767e",
        "outline-variant": "#c6c6ce",
        "surface-tint": "#545d7d",
        primary: "#010a26",
        "on-primary": "#ffffff",
        "primary-container": "#17213d",
        "on-primary-container": "#7f88aa",
        "inverse-primary": "#bcc5ea",
        secondary: "#4b42df",
        "on-secondary": "#ffffff",
        "secondary-container": "#655ef9",
        "on-secondary-container": "#fffbff",
        tertiary: "#000730",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#001964",
        "on-tertiary-container": "#6180ff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#bcc5ea",
        "on-primary-fixed": "#101a36",
        "on-primary-fixed-variant": "#3c4664",
        "secondary-fixed": "#e2dfff",
        "secondary-fixed-dim": "#c3c0ff",
        "on-secondary-fixed": "#0f0069",
        "on-secondary-fixed-variant": "#3424ca",
        "tertiary-fixed": "#dde1ff",
        "tertiary-fixed-dim": "#b8c4ff",
        "on-tertiary-fixed": "#001354",
        "on-tertiary-fixed-variant": "#0036bb",
        background: "#f7f9fd",
        "on-background": "#181c1f",
        "surface-variant": "#e0e3e6",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        headline: ["var(--font-manrope)", "Manrope", "system-ui", "sans-serif"],
        display: ["var(--font-manrope)", "Manrope", "sans-serif"],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        subtle: "0 1px 3px 0 rgba(1, 10, 38, 0.05), 0 1px 2px 0 rgba(1, 10, 38, 0.03)",
        card: "0 4px 6px -1px rgba(1, 10, 38, 0.04), 0 2px 4px -1px rgba(1, 10, 38, 0.02)",
        elevated: "0 10px 15px -3px rgba(1, 10, 38, 0.06), 0 4px 6px -2px rgba(1, 10, 38, 0.03)",
      },
    },
  },
  plugins: [],
};
export default config;
